server.port=${PORT}

#------------------Base de datos
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate

# -----------------Logs
spring.jpa.show-sql=false

#----------------JWT
security.jwt.private.key=${SECRET_KEY}
security.jwt.user.generator=NOBAMBI_SEC